package com.redhat.demos.loandemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("CreditScore")
   private int creditScore;
   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   public Applicant()
   {
   }

   public int getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(int creditScore)
   {
      this.creditScore = creditScore;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Applicant(int creditScore, java.lang.String name)
   {
      this.creditScore = creditScore;
      this.name = name;
   }

}