package com.redhat.demos.loandemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int amount;
   private boolean approved;
   private int duration;
   private double interestRate;

   public Loan()
   {
   }

   public int getAmount()
   {
      return this.amount;
   }

   public void setAmount(int amount)
   {
      this.amount = amount;
   }

   public boolean isApproved()
   {
      return this.approved;
   }

   public void setApproved(boolean approved)
   {
      this.approved = approved;
   }

   public int getDuration()
   {
      return this.duration;
   }

   public void setDuration(int duration)
   {
      this.duration = duration;
   }

   public double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(double interestRate)
   {
      this.interestRate = interestRate;
   }

   public Loan(int amount, boolean approved, int duration, double interestRate)
   {
      this.amount = amount;
      this.approved = approved;
      this.duration = duration;
      this.interestRate = interestRate;
   }

}